### ISSUE TITLE
MS-60B+ inquiry response is also '0x6e 0x00'

### ISSUE THREAD

**Issue by mungewell** [thammer/zoom-explorer#2]
Got my hands on a MS-60B+....
```
$ amidi -l
Dir Device    Name
IO  hw:2,0,0  ZOOM MS Plus Series MIDI 1

$ amidi -p hw:2,0,0 -S 'F0 7e 00 06 01 f7' -t 2 -r all_call.bin ; hexdump -C all_call.bin
15 bytes read
00000000  f0 7e 00 06 02 52 6e 00  27 00 31 2e 31 30 f7     |.~...Rn.'.1.10.|
0000000f
```

**Comment by thammer** [comment]
Cool! :-D

So the family code for the MS-60B+ is "6E 00" and the model number is "27 00".

Then we have these three pedals identified at least:
"52 6E 00 23 00" : "MS-50G+"
"52 6E 00 26 00" : "MS-70CDR+"
"52 6E 00 27 00" : "MS-60B+"

**Comment by mungewell** [comment]
Should 'https://www.waveformer.net/zoom-explorer/' do something for the MS-60B+?

I can't seem to download patches. :-(

**Comment by thammer** [comment]
Thanks for letting me know.
I have fixed a bug I think is related to this.

It'd be great if you could test and see if it works now.
* Click "Download all patches"
* Select a patch / memory slot in the patch list
* Click "Save file"
* Select another patch / memory slot in the patch list
* Click "Load file"
* Click "Save to memory slot on pedal"
* The patch you loaded from file should now be stored in the effect slot you selected last

**Comment by ttshaw1** [comment]
My take on this is that zoom explorer doesn't yet know anything about MS-60B or 60B+ effects. There's a public/zoom-effect-mappings-ms50gp.json and ms-70cdrp.json; and a src/zoom-effect-ids-ms50gp.ts and ms70cdrp.ts, but no equivalent for the MS-60B. (also an msog.json that has at least some MS50-exclusive amp effects; not sure what the file name means). So it makes sense that zoom explorer won't do much for the MS-60B at present. I believe to get full functionality we need to make an ms60.json and ms60.ts file. 

The .ts I can do with my MS50G with MS60B effects added via patched firmware, since it's just a list of effect names and their associated effect IDs. I think the effect IDs should be the same between generations, since the files for the + versions seem to work on my old MS50B. Or perhaps the patched firmware uses effects from the + generation. But either way, should be compatible. I don't suppose you've already written code to automate .ts generation @thammer ?

But the .json, which holds all the information about effect parameters, isn't feasible to do by hand; it should be automated using ZoomDevice.ts's mapParameters function, and I can't do it on my MS60B since it depends on a display-grabbing API that wasn't supported on my older pedal. 

@mungewell you interested in letting the software figure out all the parameters so we can get MS60 effects added to the tool? I gather it'll require a recompiled zoom explorer with, at the least, the button to trigger this added back in; I can give you my version, though I can't guarantee it works since I couldn't test it. If @thammer has a version with the Map Parameters button enabled that'd probably be better

**Comment by mungewell** [comment]
> I think the effect IDs should be the same between generations

NO! Zoom apparently decided to screw us, by changing to the ID/Group numbers. You may have just got lucky not to have 'hit' an overlap so far.... I don't have any original MS pedals, but the full list from the MS-60B+ is here:

https://github.com/mungewell/zoom-zt2/blob/master/zoom_fx_ms-plus/ms-60bp/effects_sort.txt


Back in sept I couldn't get this code/project running on my browser(s), but I'll give it another spin over the weekend.

@ttshaw1 I may regret offering, but sure I can try out some custom code (with guidance). 

BTW I have all the ZD2 files on PC, so if we/you can work with extracted (XML?) values I can run a script to process them. Something like `find . -name "*.ZD2" -exec python3 decode_effect.py -x {}.XML {} \;`

https://github.com/mungewell/zoom-zt2/blob/master/decode_effect.py


The last option might be to 'screen scrape' via bash/Python script over midi:
 https://github.com/mungewell/zoom-zt2/blob/master/decode_screens.py

**Comment by thammer** [comment]
I have now added the effect IDs for MS-60B+ from @mungewell's list and enabled the mapping button in ZoomExplorer.

@mungewell , if you visit https://www.waveformer.net/zoom-explorer/ and click the "Map all effects", the pedal will step through all effects and compile a list of all effect parameters by getting all screens for all parameters. It might take a couple of hours. When the process is done, you'll get a json file with all the effect parameters. If you email that to h@mmer.no, I can add it to ZoomExplorer and the editor should work for MS-60B+.

**Comment by mungewell** [comment]
It still doesn't work on my personal PC (older version of Xubuntu with Firefox and Chromium), but did work on my work PC (Windows with Chrome).
![Image](https://github.com/user-attachments/assets/bddd49e2-b20d-48b8-8919-826f493cccf4)

The 'Map all Effects' button was pressed, gave 'info window' and then process was very quick. After it gave this message:
![Image](https://github.com/user-attachments/assets/0a2d3f2e-acab-49da-8a8b-83c19c61a425)

The button label had changed to 'Save Mappings' **but** it only showed the 'info window' again and seemingly the process restarted.

If the file had been saved in the background, where would it be?

**Comment by mungewell** [comment]
Clicking around in the patches, I noticed that some where not correctly/fully decoded.

For example:
![Image](https://github.com/user-attachments/assets/583c6d2e-4676-46a1-890e-d6f5aa0b361d)
[Octaver+Vibe.60bp.zip](https://github.com/user-attachments/files/18542535/Octaver%2BVibe.60bp.zip)

This is shown on the pedal's screen as 'Bass Analogue Octaver' (Oct1/Oct2/Mod/Dry) followed by 'The Vibe' (Speed/Depth/Mode/Vol).... So there's something wonky going on.

**Comment by thammer** [comment]
It was strange that the mapping process failed. I'll do some more testing here.

Would you mind refreshing the web page, run the mapping and send me the browser log?

Hit F12, click the "Console" tab, right-click any of the messages in the log and select "Save as...".

**Comment by thammer** [comment]
And regarding the incorrectly loaded patches - you are right. The effect IDs are not unique across the MS-50G+ and MS-60B+ pedals.

Effect ID 07000020 is "Ba AnaOct" on the MS-60B+ but it is "LoopRoll" on the MS-50G+ and MS-70CDR+.  
Effect ID 060000B0 is "TheVibe" on the MS-60B+ but it is "StonePha" on the MS-50G+ and MS-70CDR+.

That's just mean.

I guess we have to use the 32-bit target number in the toplevel PTCF chunk in addition to the effect IDs to identify the effects uniquely across pedals..

I'll have to think a bit on how to solve this in ZoomExplorer.

**Comment by mungewell** [comment]
Not sure why, but it took it's time this go and stepped through all the of the effects.... there are warnings and errors in there.

[20240124_console_log.txt](https://github.com/user-attachments/files/18543096/20240124_console_log.txt)
[MS-60B+-mappings.zip](https://github.com/user-attachments/files/18543116/MS-60B%2B-mappings.zip)

**Comment by ttshaw1** [comment]
I'm afraid there's another set of effects/IDs. The ones in https://github.com/mungewell/zoom-zt2/blob/master/zoom_fx_ms-plus/ms-60bp/effects_sort.txt don't match the Bass Amp and Bass Drive effects on my device; see attached. I guess this might be where the 60B vs 60B+ question rears its ugly head; but for some reason the other effects on my device, i.e. those from MS50(+?) or MS70(+?) pedals, do match the IDs in zoom-explorer and zoom-zt2. Maybe the zoom firmware editor I used loaded the firmware with MS50 and 70 effects from + pedals, and MS60 effects from non-+ MS60B. Can't tell since it's closed source. Or maybe I have the old versions of everything, and only the MS60 effects had their IDs changed from MS60B to MS60B+?

I see a few potential solutions.  
- Have only MS-x0+ effects on my pedal. Possibly this would depend on getting [bosik's Zoom Firmware Editor](https://github.com/Barsik-Barbosik/Zoom-Firmware-Editor) to work, which it currently doesn't in my experience. Or @mungewell do you know if it's possible to use zoom-zt2 to edit firmware for old Multistomps, and if so, if old Multistomps can definitely accept + effect versions?
- Add another set of effect IDs for old (assuming that's what I have) MS60 effects, and maybe eventually old MS50s and 70s if they're not identical to the + versions. Mapping could be done either by having an intrepid volunteer load them onto a + pedal (if that's possible) and using the zoom explorer mapping function, or by using the parameter information in https://github.com/g200kg/zoom-ms-utility, which is already nicely formatted into strings.

Anyway, my usecase (which I hope other people also have) is looking increasingly like it's outside the scope of this issue. Want me to start a new one?

[ms60_effect_ids.txt](https://github.com/user-attachments/files/18544453/ms60_effect_ids.txt)

**Comment by thammer** [comment]
@ttshaw1 yes, it'd be great if you could create a new issue for supporting the MS-60B effects in ZoomExplorer. In theory it should work, but it obviously doesn't in practice :-).

The plus series pedals use a different effect format (effect format ZD2) than the original MS-series pedals like MS-60B (effect format ZDL). As far as I know, these formats are so different that it is not possible to mix them in one pedal. So I don't think the original MS series of pedals will ever support effects from the MS plus series. And vice versa - the MS plus series of pedals will probably never be able to load effects from the original MS pedals.

**Comment by thammer** [comment]
@mungewell thanks a lot for the MS-60B+ mapping file and the log. I have added the mapping to ZoomExplorer.

I hope the editor at https://www.waveformer.net/zoom-explorer/ works for the MS-60B+ pedal now.

I'll look through the log and the errors there to see if I can figure out what the problem was.

I think when people start transferring effects between the MS-60B+ and the MS-50G+ and MS-70CDR+ using your zoom-zt2 tool (or other tools), someone needs to come up with a sensible strategy for rewriting the IDs, as the IDs will have to be changed so they don't collide with existing IDs on a pedal. There are several bits in the 29-bit ID that are unused, so we could use some those to indicate which device the effect came from (as mentioned here https://github.com/mungewell/zoom-zt2/issues/87#issuecomment-2366898977). I'll make sure to support such an ID-rewriting strategy in ZoomExplorer.

**Comment by mungewell** [comment]
@thammer Awesome work, seems to be working well so I will close out this ticket.
![Image](https://github.com/user-attachments/assets/f4e4c50a-5252-4049-b4ac-3f1777b986a9)

Minor comment on formatting, some parameters are **bold** whilst others are not (4.5KHz at '-1.0' for example).
![Image](https://github.com/user-attachments/assets/27ee891e-793d-410b-84eb-47c7298c06b4)

**Comment by thammer** [comment]
Excellent!

Thanks for helping me fix this :-).
